### ISSUE TITLE
Roadmap to v1

### ISSUE THREAD

**Issue by Errorname** [Errorname/google-docs-mustaches#6]
## List of features needed for the first major release:

**Main features:**
- [x] ~Improve formatters with arguments (`formatDate('dd/mm/yyyy')`,...) and add more (uc_first, ...) (#15)~
- [x] ~Implements adding images (url? local? drive?) (#23)~
- [x] ~Externalize export in its own method (#22)~
- [x] ~Discovery (returns the list of found placeholders in a file) (#19)~
- [x] ~Strict mode (Throws error if unknown variable or formatter) (#24)~

**Documentation:**
- [x] ~Full tests of the library (#8)~
- [x] ~Add a playground for contributors (#11)~
- [x] ~Add limitations doc (#30)~

**Tooling:**
- [x] ~Add eslint/prettier config (#7)~
- [x] ~Add github check for linting and tests (#10)~
- [x] ~Ease onboarding of new contributors (#11)~

**Bugs:**
- [x] ~Fix Blob issue (#29)~
- [x] ~Fix array access issue (#16)~
- [x] ~Dev token is not refreshed (#18)~

## List of "nice-to-have" features for the first major release:

- [ ] Make a demo app
- [ ] Have a CLI wrapper for the library
- [x] ~Add comment mustaches (`{{ # blabla }}`) (#19)~
- [ ] Implements repetitions (`{{ %for myVal in myArr }}` and `{{ %row users[].name }}` for tables)
- [ ] Implements conditional blocks (`{{ %if myVar }}`)
- [ ] Add template mustaches (`{{ %define "myTemplate" }}` and `{{ @myTemplate user }}`)
